### PR TITLE
Infrastructure and Angular settings

### PR DESCRIPTION
**Pull request by donnapep**
* Add initial setup files
* Get translations from common-i18n
* Add config files
* Add e2e and unit tests for settings

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep Any reason you left JS code in `widget.html`? Otherwise :+1:

**Comment by donnapep** [comment]
@stulees I have yet to refactor the Widget. This is just for the settings. That will be up next. Thx.

**Comment by stulees** [comment]
@donnapep Okay sounds good. FYI, I'm working on the same thing for Web Page Widget within a branch and I'm already into the widget refactoring. Hope you don't mind a PR that will be for everything ...

**Comment by donnapep** [comment]
@stulees Please review. The build is failing but I'm not sure how many commits that will take to resolve so I'll want to squash everything down before I have you review the fix again.

Also, note the changes I've made to the ReadMe, most notably to the Local Development Environment Setup and Installation section to reference the `dist` folder, and to the Languages section that is just referring users to the `common-i18n` repo for now.

Thx.

**Comment by stulees** [comment]
@donnapep ReadMe looks good. I'm a bit confused about the unit test files. You're using casper and the `-e2e.html` file as a start. Should't this be protractor and no use of the `-e2e.html`?

**Comment by donnapep** [comment]
@stulees I was getting errors when my code tried to access a DOM element using PhantomJS. I guess that makes sense since there is no HTML page that gets used when running unit tests. So I had to switch to using Casper, which actually made me wonder about the wisdom of writing unit tests for Widgets in the first place. All we typically do is test that certain objects and functions exist, which I don't think are particularly useful. And with unit tests, we can only test public functions, so it's limiting. It's also really confusing trying to figure out which libraries each test file is using. If I'm confused, then third-party developers will definitely be.

So, I guess I'm proposing that we abolish unit tests since I think what's going in them are useless tests anyway, and just write robust e2e tests. Thoughts?

**Comment by stulees** [comment]
@donnapep re: getting errors, yes I don't think you should be trying to access DOM in a unit test.

I would agree that we have been able to write far more robust and useful e2e test coverage than unit test coverage when it's come to the Widget (specifically regarding Widget and not Settings). I'm not sure abolishing unit tests all together is right, I think if we actually see a good use case for unit testing a particular function or piece of code than we should still do it. If all we can see for a widget is to test certain objects and functions exist, than I would agree that this could be omitted as it's not that useful. How about we assess this on a widget to widget basis?

**Comment by donnapep** [comment]
@stulees Yes, I agree. Only include them if it makes sense to do so. I'll leave them in World Clock since they're already written. I also fixed the CCI error. Thx.

**Comment by stulees** [comment]
@donnapep Okay sounds good. So are you looking to keep the unit tests that use Casper and point to `-e2e.html` files?

**Comment by donnapep** [comment]
@stulees Yes, I'll leave it as is since it's working fine.

**Pull request merged**
